version: '2'
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=veryhardpassword
      - MYSQL_DATABASE=easyapp
      - MYSQL_USER=easyapp
      - MYSQL_PASSWORD=veryhardpassword

  application:
    image: easyappointments
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    command: dev
    ports:
      - ${APP_HOST}:80:80
      # - 9000:9000
    environment:
      - DB_HOST=database:3306
      - APP_URL=15.223.24.176
    # XDEBUG_CONFIG: 
    #   - remote_host=host.docker.internal 
    #   - remote_port=9000 
    #   - remote_enable=1
    depends_on:
      - database
    env_file:
      - .env
    restart: always
