version: '2'
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=veryhardpassword
      - MYSQL_DATABASE=easyapp
      - MYSQL_USER=easyapp
      - MYSQL_PASSWORD=veryhardpassword

  application:
    image: easyappointments
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    command: dev
    ports:
      - ${APP_HOST}:80:80
    environment:
      - DB_HOST=database:3306
      # - PHP_SITE_NAME: dev
      # - PHP_HOST_NAME: localhost:8000
      # - PHP_DOCROOT: drupal # Relative path inside the /var/www/html/ directory.
      # - PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      - PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      - XDEBUG_CONFIG: "remote_host = 172.18.0.3 remote_connect_back = 0"
    depends_on:
      - database
    env_file:
      - .env
    restart: always


# version: '3.4'

# services:
#   easyappointments:
#     image: easyappointments
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 80